name: buildOPLibs

on:
  # Triggers the workflow on push or pull request events but only for the master & develop branch
  push:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      # INSTALL PYTHON
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.8'
      
      # EXECUTE PYTHON SCRIPT  
      - name: execute py script
        run: python DeveloperTools/refreshOPLibraries.py
      
      # COMMIT CHANGES
      - name: commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated OPLibraries file" -a
          
      # PUSH TO AFFECTED BRANCH
      #- name: push changes
      #  continue-on-error: true
      #  uses: ad-m/github-push-action@v0.6.0
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        continue-on-error: true
        with:
          token: ${{ secrets.PROTECTED_PUSH }}
          #branch: ${{ github.ref }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          unprotect_reviews: true

