# This is a basic workflow to help you get started with Actions

name: buildOPLibs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master & develop branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      # INSTALL PYTHON
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.8' # install the python version needed
      
      # EXECUTE PYTHON SCRIPT  
      - name: execute py script
        run: python config/refreshOPLibraries.py # EXECUTES THE PYTHON SCIPT
      
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" | echo ${BRANCH_NAME}
        


      # COMMIT CHANGES
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated OPLibraries file" -a
          
      # PUSH TO AFFECTED BRANCH
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${BRANCH_NAME}  
